### ISSUE TITLE
BOT IS NOT WORKING

### ISSUE THREAD

**Issue by gabrielbarretosc** [nicoeg/discord-music-quizzer#1]
Hey bro, your bot is not working. When we start the quiz, the bot doesnt play any song. We cant hear any sound, even after we choose the spotify playlist that we want to guess. We dont know to fix that, and we want to have fun with our friends in the quarantine.

**Comment by nicoeg** [comment]
Youtube is blocking the requests when too many quizzes are has been started. I've tried various fixes and will keep improving it to avoid the issue.
